import React, { useEffect, useState } from 'react';
import { useAppStore } from '../../store/useAppStore';
import { fetchApiaryWithCoords } from '../../data/apiaryRepository';
import { WeatherService } from './WeatherService';
import type { InspectionWindow } from './WeatherService';
import { ChevronDown } from 'lucide-react';

import { ForecastScoreGuideModal } from './ForecastScoreGuideModal';
import { ForecastDetailModal } from './ForecastDetailModal';

export const ForecastView: React.FC = () => {
  const { selectedApiaryId, apiariesList } = useAppStore();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [forecast, setForecast] = useState<InspectionWindow[]>([]);
  const [apiaryName, setApiaryName] = useState('');
  
  // Modal states
  const [isGuideOpen, setIsGuideOpen] = useState(false);
  const [selectedCell, setSelectedCell] = useState<InspectionWindow | null>(null);

  // Auto-select if there is exactly 1 apiary
  useEffect(() => {
    if (!selectedApiaryId) {
      if (apiariesList.length === 1) {
        useAppStore.setState({ 
          selectedApiaryId: apiariesList[0].id, 
          selectedApiaryName: apiariesList[0].name 
        });
      } else {
        setLoading(false);
      }
    }
  }, [selectedApiaryId, apiariesList]);

  useEffect(() => {
    const fetchForecast = async () => {
      if (!selectedApiaryId) return;
      setLoading(true);
      setError(null);
      try {
        const apiary = await fetchApiaryWithCoords(selectedApiaryId);
        setApiaryName(apiary.name);

        const lat = apiary.lat;
        const lng = apiary.lng;

        if (lat === null || lng === null || lat === undefined || lng === undefined) {
          throw new Error('This apiary does not have coordinates. Please edit the apiary to add coordinates.');
        }

        const weatherData = await WeatherService.getWeatherForecast(lat, lng);
        const windows = WeatherService.calculateForecast(weatherData);
        setForecast(windows);

      } catch (err: any) {
        setError(err.message || 'Failed to load forecast');
      } finally {
        setLoading(false);
      }
    };

    fetchForecast();
  }, [selectedApiaryId]);

  // Group windows by date for fast layout lookup
  const gridData: Record<string, Record<number, InspectionWindow>> = {};
  const uniqueDatesSet = new Set<string>();

  forecast.forEach(w => {
      const windowDateString = w.displayDate;
      uniqueDatesSet.add(windowDateString);
      if (!gridData[windowDateString]) gridData[windowDateString] = {};
      gridData[windowDateString][w.displayHour] = w;
  });

  const sortedDates = Array.from(uniqueDatesSet).sort();
  const filteredDates = sortedDates; // forecast is already pre-filtered for future dates

  // Dynamically extract unique hours generated by calculation
  const initialTimeSlots = Array.from(new Set(forecast.map(w => w.displayHour))).sort((a, b) => a - b);
  const timeSlots: number[] = [...initialTimeSlots];

  // If trailing lines are entirely too close to sunset for all days of the week, omit them
  while (timeSlots.length > 0) {
      const lastHour = timeSlots[timeSlots.length - 1];
      const allTooLate = filteredDates.every(dateStr => {
          const w = gridData[dateStr]?.[lastHour];
          if (!w) return true;
          return w.issuesV2.some(issue => issue.toLowerCase().includes('sunset'));
      });

      if (allTooLate) {
          timeSlots.pop();
      } else {
          break;
      }
  }

  const getScoreColorV2 = (classification: 'Optimal' | 'Viable' | 'Inadvisable') => {
      if (classification === 'Optimal') return 'bg-green-600';
      if (classification === 'Viable') return 'bg-amber-400';
      return 'bg-red-500';
  };

  const formatTimeSlot = (hour: number) => {
      if (hour === 0 || hour === 24) return '12am';
      if (hour === 12) return '12pm';
      if (hour < 12) return `${hour}am`;
      return `${hour - 12}pm`;
  };

  return (
    <div className="w-full flex-1 overflow-y-auto flex flex-col items-center p-2 sm:p-4 space-y-4 animate-in slide-in-from-right-4 duration-300 relative">
      
      {/* Header */}
      <div className="w-full max-w-[800px] flex justify-center items-center py-2 relative">
        <div className="text-center">
          <h2 className="text-2xl font-black text-[#8B4513] dark:text-amber-500">Hive Forecast</h2>
          {selectedApiaryId && apiariesList.length > 1 ? (
            <div className="relative inline-flex items-center gap-1 mt-0.5 justify-center">
              <select
                value={selectedApiaryId}
                onChange={(e) => {
                  const selected = apiariesList.find(a => a.id === e.target.value);
                  if (selected) {
                    useAppStore.setState({ selectedApiaryId: selected.id, selectedApiaryName: selected.name });
                  }
                }}
                className="bg-transparent text-sm font-bold text-[var(--color-text-muted)] border-none focus:outline-none appearance-none pr-5 cursor-pointer text-center outline-none"
              >
                {apiariesList.map(a => (
                  <option key={a.id} value={a.id} className="text-black dark:text-white bg-[var(--color-bg)]">
                    {a.name}
                  </option>
                ))}
              </select>
              <div className="absolute right-0 pointer-events-none text-[var(--color-text-muted)]">
                <ChevronDown size={14} />
              </div>
            </div>
          ) : (
            <p className="text-sm font-bold text-[var(--color-text-muted)]">{selectedApiaryId ? apiaryName : 'Select Location'}</p>
          )}
        </div>
      </div>

      <div className="w-full max-w-[800px]">
        {!selectedApiaryId ? (
          apiariesList.length === 0 ? (
            <div className="bg-[var(--color-input-bg)] rounded-3xl p-8 text-center shadow-sm border border-[var(--color-card-border)]">
              <p className="font-bold text-[var(--color-text)] mb-2">No Apiaries Found</p>
              <p className="text-sm text-[var(--color-text-muted)]">Please create an apiary yard first to view the weather forecast.</p>
            </div>
          ) : (
            <div className="bg-[var(--color-input-bg)] rounded-3xl p-8 flex flex-col items-center justify-center gap-6 shadow-sm border border-[var(--color-card-border)] w-full max-w-md mx-auto">
              <div className="text-center">
                <h3 className="text-lg font-black text-[var(--color-text)]">Select Apiary</h3>
                <p className="text-xs text-[var(--color-text-muted)] font-medium mt-1">
                  Choose an apiary to view the 7-day inspection forecast.
                </p>
              </div>
              <div className="w-full flex flex-col gap-2">
                {apiariesList.map(a => (
                  <button
                    key={a.id}
                    onClick={() => {
                      useAppStore.setState({ selectedApiaryId: a.id, selectedApiaryName: a.name });
                    }}
                    className="w-full card p-4 text-center font-bold text-sm hover:border-[var(--color-primary)] active:scale-98 transition-all"
                  >
                    {a.name}
                  </button>
                ))}
              </div>
            </div>
          )
        ) : loading ? (
          <div className="bg-[var(--color-input-bg)] rounded-3xl p-12 flex flex-col items-center justify-center gap-4 shadow-sm border border-[var(--color-card-border)]">
            <div className="w-8 h-8 border-4 border-[#8B4513] border-t-transparent rounded-full animate-spin"></div>
            <p className="font-bold text-[#8B4513] animate-pulse">Analyzing meteorological data...</p>
          </div>
        ) : error ? (
          <div className="bg-[var(--color-input-bg)] rounded-3xl p-8 text-center border-red-200 shadow-sm border">
             <p className="text-red-600 font-bold mb-2">Error</p>
             <p className="text-sm text-red-500">{error}</p>
          </div>
        ) : (
          <div className="w-full flex flex-col items-center space-y-4">
              
              {/* V2 Scoring Legend */}
              <div className="flex flex-col items-center justify-center text-[10px] sm:text-xs bg-white/70 dark:bg-[#1E1E1E]/70 p-2 sm:p-4 rounded-2xl border border-[var(--color-card-border)] shadow-sm max-w-sm mx-auto backdrop-blur-sm">
                  <span className="font-extrabold text-[#8B4513] dark:text-amber-500 mb-1 sm:mb-1.5 uppercase tracking-wider text-[9px]">Decision Points (0-9)</span>
                  <div className="flex flex-wrap gap-x-3 gap-y-1 justify-center font-bold text-[var(--color-text-muted)]">
                      <div className="flex items-center gap-1.5"><div className="w-2.5 h-2.5 rounded-full bg-green-600"></div>Optimal 7-9</div>
                      <div className="flex items-center gap-1.5"><div className="w-2.5 h-2.5 rounded-full bg-amber-400"></div>Viable 4-6</div>
                      <div className="flex items-center gap-1.5"><div className="w-2.5 h-2.5 rounded-full bg-red-500"></div>Inadvisable 0-3</div>
                  </div>
              </div>

              {/* Action Links */}
              <div className="flex items-center justify-center gap-2 text-xs font-bold mt-1">
                  <span className="text-[var(--color-text-muted)] italic">Tap a cell for details</span>
                  <span className="text-[var(--color-text-muted)] mx-1">|</span>
                  <button 
                    onClick={() => setIsGuideOpen(true)}
                    className="text-amber-600 dark:text-amber-500 hover:text-amber-700 underline decoration-dotted underline-offset-4 transition-colors"
                  >
                    How are scores calculated?
                  </button>
              </div>

              {/* The Grid Container - Centered and Square overall */}
              <div className="w-full flex flex-col items-center sm:max-w-[520px] mx-auto px-1 sm:px-2 mt-2">
                  <div className="rounded-xl shadow-md border border-[var(--color-card-border)] w-full bg-[var(--color-input-bg)] overflow-hidden">
                      <table className="border-collapse w-full text-xs table-fixed">
                          <thead>
                              <tr className="bg-[var(--color-bg-raised)]">
                                  <th className="border-b border-r border-[var(--color-card-border)] py-1.5 sm:py-2.5 font-bold sticky left-0 bg-[var(--color-bg-raised)] z-10 text-[#8B4513] dark:text-amber-500 w-[46px] sm:w-20 text-center">Time</th>
                                  {filteredDates.map(dateStr => {
                                      const date = new Date(dateStr + 'T12:00:00');
                                      const getCompactDayStr = (dStr: string) => {
                                          const d = new Date(dStr + 'T12:00:00');
                                          const wd = d.toLocaleDateString('en-US', { weekday: 'short' });
                                          if (wd === 'Thu') return 'Th';
                                          if (wd === 'Sat') return 'Sa';
                                          if (wd === 'Sun') return 'Su';
                                          return wd.slice(0, 2); // Tu, We, Fr, Mo
                                      };
                                      return (
                                          <th key={dateStr} className="border-b border-[var(--color-card-border)] py-1.5 sm:py-2.5 px-0.5 text-center min-w-0">
                                              <div className="font-extrabold text-[#8B4513] dark:text-amber-500 hidden sm:block">
                                                  {date.toLocaleDateString('en-US', { weekday: 'short' })}
                                              </div>
                                              <div className="font-extrabold text-[#8B4513] dark:text-amber-500 block sm:hidden text-[11px]">
                                                  {getCompactDayStr(dateStr)}
                                              </div>
                                              <div className="text-[9px] sm:text-[10px] text-[var(--color-text-muted)] font-bold leading-none mt-0.5">
                                                  {date.toLocaleDateString('en-US', { month: 'numeric', day: 'numeric' })}
                                              </div>
                                          </th>
                                      );
                                  })}
                              </tr>
                          </thead>
                          <tbody>
                              {timeSlots.map(hour => (
                                  <tr key={hour} className="hover:bg-amber-500/5">
                                      <td className="border-b border-r border-[var(--color-card-border)] h-7 sm:h-10 py-0 font-bold sticky left-0 bg-[var(--color-input-bg)] z-10 text-[var(--color-text-muted)] text-[10px] sm:text-[10px] w-[46px] sm:w-20 text-center">
                                          {formatTimeSlot(hour)}
                                      </td>
                                      {filteredDates.map(dateStr => {
                                          const window = gridData[dateStr]?.[hour];
                                          if (!window) {
                                              return <td key={dateStr} className="border-b border-[var(--color-card-border)] bg-gray-50/20 h-7 sm:h-10 min-w-0"></td>;
                                          }

                                          const isFail = window.classificationV2 === 'Inadvisable';
                                          const textColor = isFail ? 'text-black' : 'text-white';

                                          return (
                                              <td
                                                  key={dateStr}
                                                  className={`border-b border-[var(--color-card-border)] h-7 sm:h-10 cursor-pointer hover:opacity-90 transition-opacity min-w-0 ${getScoreColorV2(window.classificationV2)}`}
                                                  onClick={() => setSelectedCell(window)}
                                              >
                                                  <div className={`flex items-center justify-center h-full font-black text-xs sm:text-sm ${textColor}`}>
                                                      {window.scoreV2}
                                                  </div>
                                              </td>
                                          );
                                      })}
                                  </tr>
                              ))}
                          </tbody>
                      </table>
                  </div>
              </div>
              
              <p className="text-[10px] font-bold text-[var(--color-text-muted)] italic mt-2 w-full text-center">
                  White numerals = OK to inspect • Black numerals = Not recommended
              </p>
          </div>
        )}
      </div>

      <ForecastScoreGuideModal isOpen={isGuideOpen} onClose={() => setIsGuideOpen(false)} />
      <ForecastDetailModal isOpen={!!selectedCell} onClose={() => setSelectedCell(null)} window={selectedCell} />

    </div>
  );
};
