-- ============================================================================
-- Seed plant lists for the ecoregions Ron's users actually occupy.
--
-- GENERATED by scripts/gen-seed-zone-plants.mjs - edit that and regenerate rather
-- than editing this file by hand.
--
-- Zone selection: of the 13 located apiaries in the database, these five Level IV
-- ecoregions cover nine. The remaining four are one apiary each and follow later.
--
-- Inclusion rule: a plant earns a place only if a beekeeper would want to know it is
-- blooming BECAUSE IT MIGHT MEAN NECTAR. Abundance is not the criterion, so
-- wind-pollinated species are excluded however dominant - cottonwood and Siberian elm
-- in Albuquerque, pinon, juniper, Gambel oak and mountain mahogany in the Sandias.
-- Yucca is excluded as well: it is pollinated by yucca moths, not honeybees.
--
-- confidence='low' rows are shipped deliberately. A visible, wrong entry invites
-- correction; a missing one is invisible. 23e is the weakest list and most needs
-- review by a beekeeper who works that zone.
--
-- Bloom windows are calendar priors. GDD columns are intentionally left null and are
-- populated later, at which point the dates become elastic to the actual season -
-- which is the whole point of GDD in a year like 2026, when a 90F March pulled
-- Albuquerque bloom weeks early.
--
-- Idempotent: safe to re-run. Apply to "Beekeeper Dev v2" first.
-- ============================================================================

-- Species master.
insert into public.plants (common_name, scientific_name) values ('Alfalfa', 'Medicago sativa')
  on conflict (lower(common_name)) do nothing;
insert into public.plants (common_name, scientific_name) values ('Russian Olive', 'Elaeagnus angustifolia')
  on conflict (lower(common_name)) do nothing;
insert into public.plants (common_name, scientific_name) values ('Salt Cedar', 'Tamarix ramosissima')
  on conflict (lower(common_name)) do nothing;
insert into public.plants (common_name, scientific_name) values ('Chamisa (Rubber Rabbitbrush)', 'Ericameria nauseosa')
  on conflict (lower(common_name)) do nothing;
insert into public.plants (common_name, scientific_name) values ('Yellow Sweet Clover', 'Melilotus officinalis')
  on conflict (lower(common_name)) do nothing;
insert into public.plants (common_name, scientific_name) values ('White Sweet Clover', 'Melilotus albus')
  on conflict (lower(common_name)) do nothing;
insert into public.plants (common_name, scientific_name) values ('White Clover', 'Trifolium repens')
  on conflict (lower(common_name)) do nothing;
insert into public.plants (common_name, scientific_name) values ('Willow', 'Salix spp.')
  on conflict (lower(common_name)) do nothing;
insert into public.plants (common_name, scientific_name) values ('Fruit Trees', 'Prunus / Malus spp.')
  on conflict (lower(common_name)) do nothing;
insert into public.plants (common_name, scientific_name) values ('Sunflower', 'Helianthus spp.')
  on conflict (lower(common_name)) do nothing;
insert into public.plants (common_name, scientific_name) values ('Mexican Hat', 'Ratibida columnifera')
  on conflict (lower(common_name)) do nothing;
insert into public.plants (common_name, scientific_name) values ('Desert Willow', 'Chilopsis linearis')
  on conflict (lower(common_name)) do nothing;
insert into public.plants (common_name, scientific_name) values ('Russian Sage', 'Salvia yangii')
  on conflict (lower(common_name)) do nothing;
insert into public.plants (common_name, scientific_name) values ('Snakeweed', 'Gutierrezia sarothrae')
  on conflict (lower(common_name)) do nothing;
insert into public.plants (common_name, scientific_name) values ('Desert Marigold', 'Baileya multiradiata')
  on conflict (lower(common_name)) do nothing;
insert into public.plants (common_name, scientific_name) values ('New Mexico Locust', 'Robinia neomexicana')
  on conflict (lower(common_name)) do nothing;
insert into public.plants (common_name, scientific_name) values ('Cholla', 'Cylindropuntia spp.')
  on conflict (lower(common_name)) do nothing;
insert into public.plants (common_name, scientific_name) values ('Apache Plume', 'Fallugia paradoxa')
  on conflict (lower(common_name)) do nothing;
insert into public.plants (common_name, scientific_name) values ('Fendler''s Ceanothus', 'Ceanothus fendleri')
  on conflict (lower(common_name)) do nothing;
insert into public.plants (common_name, scientific_name) values ('Wild Bergamot', 'Monarda fistulosa')
  on conflict (lower(common_name)) do nothing;
insert into public.plants (common_name, scientific_name) values ('Rocky Mountain Bee Plant', 'Cleome serrulata')
  on conflict (lower(common_name)) do nothing;
insert into public.plants (common_name, scientific_name) values ('Tulip Poplar', 'Liriodendron tulipifera')
  on conflict (lower(common_name)) do nothing;
insert into public.plants (common_name, scientific_name) values ('Black Locust', 'Robinia pseudoacacia')
  on conflict (lower(common_name)) do nothing;
insert into public.plants (common_name, scientific_name) values ('Blackberry', 'Rubus spp.')
  on conflict (lower(common_name)) do nothing;
insert into public.plants (common_name, scientific_name) values ('Privet', 'Ligustrum sinense')
  on conflict (lower(common_name)) do nothing;
insert into public.plants (common_name, scientific_name) values ('Goldenrod', 'Solidago spp.')
  on conflict (lower(common_name)) do nothing;
insert into public.plants (common_name, scientific_name) values ('Aster', 'Symphyotrichum spp.')
  on conflict (lower(common_name)) do nothing;
insert into public.plants (common_name, scientific_name) values ('Red Maple', 'Acer rubrum')
  on conflict (lower(common_name)) do nothing;
insert into public.plants (common_name, scientific_name) values ('Partridge Pea', 'Chamaecrista fasciculata')
  on conflict (lower(common_name)) do nothing;
insert into public.plants (common_name, scientific_name) values ('Linden / Basswood', 'Tilia spp.')
  on conflict (lower(common_name)) do nothing;
insert into public.plants (common_name, scientific_name) values ('Dandelion', 'Taraxacum officinale')
  on conflict (lower(common_name)) do nothing;


-- 22g Rio Grande Floodplain
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '22g', id, '05-01', '06-15', '09-15', 0.9, 'NMSU Honey Bees in New Mexico + Ron Nolte field observation 2026-08', 'high'
  from public.plants where lower(common_name) = lower('Alfalfa')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '22g', id, '05-01', '05-20', '06-15', 0.9, 'NMSU Honey Bees in New Mexico', 'high'
  from public.plants where lower(common_name) = lower('Russian Olive')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '22g', id, '04-15', '06-15', '09-15', 0.7, 'NMSU Honey Bees in New Mexico', 'high'
  from public.plants where lower(common_name) = lower('Salt Cedar')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '22g', id, '08-15', '09-15', '10-31', 0.9, 'USDA NRCS Plant Materials Technical Note 71 (Los Lunas PMC) + Ron Nolte field observation 2026-08', 'high'
  from public.plants where lower(common_name) = lower('Chamisa (Rubber Rabbitbrush)')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '22g', id, '05-01', '06-01', '07-15', 0.9, 'USDA NRCS Plant Materials Technical Note 71 (Los Lunas PMC)', 'medium'
  from public.plants where lower(common_name) = lower('Yellow Sweet Clover')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '22g', id, '04-15', '06-01', '09-15', 0.5, 'NMSU Honey Bees in New Mexico', 'medium'
  from public.plants where lower(common_name) = lower('White Clover')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '22g', id, '02-15', '03-10', '04-05', 0.5, 'USDA NRCS Plant Materials Technical Note 71 (Los Lunas PMC)', 'medium'
  from public.plants where lower(common_name) = lower('Willow')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '22g', id, '03-10', '04-01', '04-25', 0.5, 'USDA NRCS Plant Materials Technical Note 71 (Los Lunas PMC)', 'medium'
  from public.plants where lower(common_name) = lower('Fruit Trees')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '22g', id, '07-01', '08-15', '09-30', 0.5, 'USDA NRCS Plant Materials Technical Note 71 (Los Lunas PMC)', 'medium'
  from public.plants where lower(common_name) = lower('Sunflower')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '22g', id, '06-01', '07-15', '09-15', 0.3, 'USDA NRCS Plant Materials Technical Note 71 (Los Lunas PMC) + Ron Nolte field observation 2026-08', 'high'
  from public.plants where lower(common_name) = lower('Mexican Hat')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;

-- 22m Albuquerque Basin
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '22m', id, '08-15', '09-15', '10-31', 0.9, 'USDA NRCS Plant Materials Technical Note 71 (Los Lunas PMC)', 'high'
  from public.plants where lower(common_name) = lower('Chamisa (Rubber Rabbitbrush)')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '22m', id, '05-01', '06-01', '07-15', 0.9, 'USDA NRCS Plant Materials Technical Note 71 (Los Lunas PMC)', 'medium'
  from public.plants where lower(common_name) = lower('Yellow Sweet Clover')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '22m', id, '05-01', '06-15', '09-15', 0.9, 'NMSU Honey Bees in New Mexico', 'medium'
  from public.plants where lower(common_name) = lower('Alfalfa')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '22m', id, '06-01', '07-01', '08-15', 0.5, 'NMSU Honey Bees in New Mexico', 'medium'
  from public.plants where lower(common_name) = lower('Desert Willow')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '22m', id, '06-01', '07-15', '09-15', 0.5, 'NMSU Honey Bees in New Mexico', 'medium'
  from public.plants where lower(common_name) = lower('Russian Sage')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '22m', id, '07-01', '08-15', '09-30', 0.5, 'USDA NRCS Plant Materials Technical Note 71 (Los Lunas PMC)', 'medium'
  from public.plants where lower(common_name) = lower('Sunflower')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '22m', id, '08-15', '09-15', '10-31', 0.5, 'USDA NRCS Plant Materials Technical Note 71 (Los Lunas PMC)', 'medium'
  from public.plants where lower(common_name) = lower('Snakeweed')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '22m', id, '03-10', '04-01', '04-25', 0.5, 'USDA NRCS Plant Materials Technical Note 71 (Los Lunas PMC)', 'medium'
  from public.plants where lower(common_name) = lower('Fruit Trees')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '22m', id, '04-01', '06-01', '10-31', 0.3, 'USDA NRCS Plant Materials Technical Note 71 (Los Lunas PMC)', 'medium'
  from public.plants where lower(common_name) = lower('Desert Marigold')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '22m', id, '06-01', '07-15', '09-15', 0.3, 'USDA NRCS Plant Materials Technical Note 71 (Los Lunas PMC)', 'medium'
  from public.plants where lower(common_name) = lower('Mexican Hat')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;

-- 23e Conifer Woodlands and Savannas
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '23e', id, '05-10', '06-01', '06-30', 0.9, 'USDA NRCS Plant Materials Technical Note 71 (Los Lunas PMC)', 'medium'
  from public.plants where lower(common_name) = lower('New Mexico Locust')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '23e', id, '08-20', '09-20', '10-31', 0.9, 'USDA NRCS Plant Materials Technical Note 71 (Los Lunas PMC)', 'medium'
  from public.plants where lower(common_name) = lower('Chamisa (Rubber Rabbitbrush)')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '23e', id, '05-01', '05-25', '06-30', 0.7, 'Ron Nolte field observation 2026-08', 'medium'
  from public.plants where lower(common_name) = lower('Cholla')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '23e', id, '05-01', '06-15', '09-15', 0.5, 'USDA NRCS Plant Materials Technical Note 71 (Los Lunas PMC)', 'medium'
  from public.plants where lower(common_name) = lower('Apache Plume')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '23e', id, '05-15', '06-15', '07-15', 0.5, 'Inferred from regional flora - NOT yet validated', 'low'
  from public.plants where lower(common_name) = lower('Fendler''s Ceanothus')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '23e', id, '06-15', '07-15', '08-31', 0.5, 'USDA NRCS Plant Materials Technical Note 71 (Los Lunas PMC)', 'low'
  from public.plants where lower(common_name) = lower('Wild Bergamot')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '23e', id, '06-15', '07-20', '08-31', 0.5, 'USDA NRCS Plant Materials Technical Note 71 (Los Lunas PMC)', 'medium'
  from public.plants where lower(common_name) = lower('Rocky Mountain Bee Plant')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '23e', id, '07-01', '08-15', '09-30', 0.5, 'USDA NRCS Plant Materials Technical Note 71 (Los Lunas PMC)', 'medium'
  from public.plants where lower(common_name) = lower('Sunflower')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '23e', id, '08-15', '09-15', '10-31', 0.5, 'USDA NRCS Plant Materials Technical Note 71 (Los Lunas PMC)', 'medium'
  from public.plants where lower(common_name) = lower('Snakeweed')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '23e', id, '04-01', '04-20', '05-15', 0.5, 'Inferred from regional flora - NOT yet validated', 'low'
  from public.plants where lower(common_name) = lower('Fruit Trees')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;

-- 71i Inner Nashville Basin
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '71i', id, '04-15', '05-05', '05-31', 0.9, 'Nashville Area Beekeepers Association', 'high'
  from public.plants where lower(common_name) = lower('Tulip Poplar')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '71i', id, '04-01', '04-08', '04-25', 0.9, 'Nashville Area Beekeepers Association', 'high'
  from public.plants where lower(common_name) = lower('Black Locust')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '71i', id, '04-20', '05-26', '08-15', 0.9, 'Nashville Area Beekeepers Association', 'high'
  from public.plants where lower(common_name) = lower('White Clover')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '71i', id, '04-25', '05-15', '06-05', 0.9, 'Nashville Area Beekeepers Association', 'high'
  from public.plants where lower(common_name) = lower('Blackberry')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '71i', id, '05-01', '05-15', '05-31', 0.7, 'Nashville Area Beekeepers Association', 'high'
  from public.plants where lower(common_name) = lower('Privet')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '71i', id, '08-01', '09-01', '10-31', 0.9, 'Nashville Area Beekeepers Association + Ron Nolte field observation 2026-08', 'high'
  from public.plants where lower(common_name) = lower('Goldenrod')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '71i', id, '09-01', '10-01', '11-05', 0.5, 'Nashville Area Beekeepers Association', 'high'
  from public.plants where lower(common_name) = lower('Aster')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '71i', id, '02-10', '02-23', '03-20', 0.5, 'Nashville Area Beekeepers Association', 'high'
  from public.plants where lower(common_name) = lower('Red Maple')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '71i', id, '03-01', '04-01', '04-25', 0.5, 'Nashville Area Beekeepers Association', 'high'
  from public.plants where lower(common_name) = lower('Fruit Trees')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '71i', id, '07-01', '08-15', '09-30', 0.5, 'Inferred from regional flora - NOT yet validated', 'low'
  from public.plants where lower(common_name) = lower('Partridge Pea')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;

-- 25d Flat to Rolling Plains (Front Range)
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '25d', id, '06-01', '07-01', '09-15', 0.9, 'Colorado State Beekeepers Association / regional sources', 'high'
  from public.plants where lower(common_name) = lower('Alfalfa')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '25d', id, '06-01', '07-01', '08-15', 0.9, 'Colorado State Beekeepers Association / regional sources', 'high'
  from public.plants where lower(common_name) = lower('White Sweet Clover')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '25d', id, '05-15', '06-15', '07-31', 0.9, 'Colorado State Beekeepers Association / regional sources', 'medium'
  from public.plants where lower(common_name) = lower('Yellow Sweet Clover')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '25d', id, '05-10', '05-30', '06-20', 0.7, 'Colorado State Beekeepers Association / regional sources', 'medium'
  from public.plants where lower(common_name) = lower('Russian Olive')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '25d', id, '06-10', '06-25', '07-10', 0.7, 'Colorado State Beekeepers Association / regional sources', 'medium'
  from public.plants where lower(common_name) = lower('Linden / Basswood')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '25d', id, '03-15', '04-20', '05-31', 0.5, 'Colorado State Beekeepers Association / regional sources', 'high'
  from public.plants where lower(common_name) = lower('Dandelion')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '25d', id, '04-10', '05-01', '05-25', 0.5, 'Colorado State Beekeepers Association / regional sources', 'high'
  from public.plants where lower(common_name) = lower('Fruit Trees')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '25d', id, '07-01', '08-15', '09-30', 0.5, 'Colorado State Beekeepers Association / regional sources', 'medium'
  from public.plants where lower(common_name) = lower('Sunflower')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '25d', id, '08-15', '09-15', '10-15', 0.5, 'Colorado State Beekeepers Association / regional sources', 'medium'
  from public.plants where lower(common_name) = lower('Chamisa (Rubber Rabbitbrush)')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
insert into public.zone_plants (zone_level, zone_code, plant_id, bloom_start, bloom_peak, bloom_end, nectar_value, source, confidence)
  select 'l4', '25d', id, '08-01', '09-01', '09-30', 0.5, 'Colorado State Beekeepers Association / regional sources', 'high'
  from public.plants where lower(common_name) = lower('Goldenrod')
  on conflict (zone_level, coalesce(zone_code, ''), plant_id) do nothing;
